server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/plain applcation/x-javascript application/javascript text/css text/xml application/xml application/xml+rss text/javascript application/x-httpd-php
spring:
  application:
    name: Leryn Authorization Server
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      pool-name: DateHikariCP
      maximum-pool-size: 50
      max-lifetime: 18000
      idle-timeout: 18000
      auto-commit: true
      minimum-idle: 5
      connection-timeout: 3000
      connection-test-query: select 1 from dual
  jackson:
    date-format: yyyy-MM-dd HH:mm:SS
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 121.196.30.39
    port: 6379
    database: 0
    password: redis123456
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 8
        max-wait: -1ms
      shutdown-timeout: 100ms