/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * API表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Api implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        url;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public Api() {}

    public Api(Api value) {
        this.id = value.id;
        this.url = value.url;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public Api(
        Integer       id,
        String        url,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.url = url;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.api.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.api.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.api.url</code>. Restful风格的API URL
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>idaas.api.url</code>. Restful风格的API URL
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for <code>idaas.api.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.api.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.api.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.api.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Api (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
