/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authority implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       authorityId;
    private String        name;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public Authority() {}

    public Authority(Authority value) {
        this.id = value.id;
        this.authorityId = value.authorityId;
        this.name = value.name;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public Authority(
        Integer       id,
        Integer       authorityId,
        String        name,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.authorityId = authorityId;
        this.name = name;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.authority.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.authority.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.authority.authority_id</code>. 权限ID
     */
    public Integer getAuthorityId() {
        return this.authorityId;
    }

    /**
     * Setter for <code>idaas.authority.authority_id</code>. 权限ID
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * Getter for <code>idaas.authority.name</code>. 权限名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>idaas.authority.name</code>. 权限名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>idaas.authority.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.authority.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.authority.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.authority.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authority (");

        sb.append(id);
        sb.append(", ").append(authorityId);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
