/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 角色-权限关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleAuthorityRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       roleId;
    private Integer       authorityId;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public RoleAuthorityRelation() {}

    public RoleAuthorityRelation(RoleAuthorityRelation value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.authorityId = value.authorityId;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public RoleAuthorityRelation(
        Integer       id,
        Integer       roleId,
        Integer       authorityId,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.roleId = roleId;
        this.authorityId = authorityId;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.role_authority_relation.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.role_authority_relation.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.role_authority_relation.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>idaas.role_authority_relation.role_id</code>. 角色ID
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>idaas.role_authority_relation.authority_id</code>. 权限ID
     */
    public Integer getAuthorityId() {
        return this.authorityId;
    }

    /**
     * Setter for <code>idaas.role_authority_relation.authority_id</code>. 权限ID
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * Getter for <code>idaas.role_authority_relation.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.role_authority_relation.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.role_authority_relation.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.role_authority_relation.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoleAuthorityRelation (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(authorityId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
