/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       roleId;
    private String        name;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.name = value.name;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public Role(
        Integer       id,
        Integer       roleId,
        String        name,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.roleId = roleId;
        this.name = name;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.role.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.role.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.role.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>idaas.role.role_id</code>. 角色ID
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>idaas.role.name</code>. 角色名
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>idaas.role.name</code>. 角色名
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>idaas.role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.role.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.role.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
