/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private String        username;
    private String        password;
    private String        salt;
    private Boolean       passwordActivated;
    private String        avatar;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.userId = value.userId;
        this.username = value.username;
        this.password = value.password;
        this.salt = value.salt;
        this.passwordActivated = value.passwordActivated;
        this.avatar = value.avatar;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public User(
        Integer       id,
        Integer       userId,
        String        username,
        String        password,
        String        salt,
        Boolean       passwordActivated,
        String        avatar,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.salt = salt;
        this.passwordActivated = passwordActivated;
        this.avatar = avatar;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.user.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.user.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.user.user_id</code>. 用户ID
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>idaas.user.user_id</code>. 用户ID
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>idaas.user.username</code>. 用户名
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>idaas.user.username</code>. 用户名
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>idaas.user.password</code>. 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>idaas.user.password</code>. 密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>idaas.user.salt</code>. 盐(8位随机盐)
     */
    public String getSalt() {
        return this.salt;
    }

    /**
     * Setter for <code>idaas.user.salt</code>. 盐(8位随机盐)
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * Getter for <code>idaas.user.password_activated</code>. 密码是否激活
     */
    public Boolean getPasswordActivated() {
        return this.passwordActivated;
    }

    /**
     * Setter for <code>idaas.user.password_activated</code>. 密码是否激活
     */
    public void setPasswordActivated(Boolean passwordActivated) {
        this.passwordActivated = passwordActivated;
    }

    /**
     * Getter for <code>idaas.user.avatar</code>. 头像URL
     */
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * Setter for <code>idaas.user.avatar</code>. 头像URL
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * Getter for <code>idaas.user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.user.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.user.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.user.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(passwordActivated);
        sb.append(", ").append(avatar);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
