/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户组表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private Integer       parentId;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public UserGroup() {}

    public UserGroup(UserGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.parentId = value.parentId;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public UserGroup(
        Integer       id,
        String        name,
        Integer       parentId,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>idaas.user_group.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.user_group.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.user_group.name</code>. 用户组名
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>idaas.user_group.name</code>. 用户组名
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>idaas.user_group.parent_id</code>.
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>idaas.user_group.parent_id</code>.
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * Getter for <code>idaas.user_group.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.user_group.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.user_group.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>idaas.user_group.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
