/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户-角色关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private Integer       roleId;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public UserRoleRelation() {}

    public UserRoleRelation(UserRoleRelation value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleId = value.roleId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public UserRoleRelation(
        Integer       id,
        Integer       userId,
        Integer       roleId,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>idaas.user_role_relation.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>idaas.user_role_relation.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>idaas.user_role_relation.user_id</code>. 用户ID(员工号)
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>idaas.user_role_relation.user_id</code>. 用户ID(员工号)
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>idaas.user_role_relation.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>idaas.user_role_relation.role_id</code>. 角色ID
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>idaas.user_role_relation.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>idaas.user_role_relation.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>idaas.user_role_relation.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>idaas.user_role_relation.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoleRelation (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
