/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.ApiRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * API表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Api extends TableImpl<ApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.api</code>
     */
    public static final Api API = new Api();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApiRecord> getRecordType() {
        return ApiRecord.class;
    }

    /**
     * The column <code>idaas.api.id</code>. 代理主键
     */
    public final TableField<ApiRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.api.url</code>. Restful风格的API URL
     */
    public final TableField<ApiRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(100).nullable(false), this, "Restful风格的API URL");

    /**
     * The column <code>idaas.api.create_time</code>. 创建时间
     */
    public final TableField<ApiRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.api.modified_time</code>. 修改时间
     */
    public final TableField<ApiRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private Api(Name alias, Table<ApiRecord> aliased) {
        this(alias, aliased, null);
    }

    private Api(Name alias, Table<ApiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("API表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.api</code> table reference
     */
    public Api(String alias) {
        this(DSL.name(alias), API);
    }

    /**
     * Create an aliased <code>idaas.api</code> table reference
     */
    public Api(Name alias) {
        this(alias, API);
    }

    /**
     * Create a <code>idaas.api</code> table reference
     */
    public Api() {
        this(DSL.name("api"), null);
    }

    public <O extends Record> Api(Table<O> child, ForeignKey<O, ApiRecord> key) {
        super(child, key, API);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<ApiRecord, Integer> getIdentity() {
        return (Identity<ApiRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApiRecord> getPrimaryKey() {
        return Keys.KEY_API_PRIMARY;
    }

    @Override
    public List<UniqueKey<ApiRecord>> getKeys() {
        return Arrays.<UniqueKey<ApiRecord>>asList(Keys.KEY_API_PRIMARY);
    }

    @Override
    public Api as(String alias) {
        return new Api(DSL.name(alias), this);
    }

    @Override
    public Api as(Name alias) {
        return new Api(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Api rename(String name) {
        return new Api(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Api rename(Name name) {
        return new Api(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
