/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.AuthorityMenuRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-菜单关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityMenuRelation extends TableImpl<AuthorityMenuRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.authority_menu_relation</code>
     */
    public static final AuthorityMenuRelation AUTHORITY_MENU_RELATION = new AuthorityMenuRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorityMenuRelationRecord> getRecordType() {
        return AuthorityMenuRelationRecord.class;
    }

    /**
     * The column <code>idaas.authority_menu_relation.id</code>. 代理主键
     */
    public final TableField<AuthorityMenuRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.authority_menu_relation.create_time</code>. 创建时间
     */
    public final TableField<AuthorityMenuRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.authority_menu_relation.modified_time</code>. 修改时间
     */
    public final TableField<AuthorityMenuRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private AuthorityMenuRelation(Name alias, Table<AuthorityMenuRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorityMenuRelation(Name alias, Table<AuthorityMenuRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-菜单关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.authority_menu_relation</code> table reference
     */
    public AuthorityMenuRelation(String alias) {
        this(DSL.name(alias), AUTHORITY_MENU_RELATION);
    }

    /**
     * Create an aliased <code>idaas.authority_menu_relation</code> table reference
     */
    public AuthorityMenuRelation(Name alias) {
        this(alias, AUTHORITY_MENU_RELATION);
    }

    /**
     * Create a <code>idaas.authority_menu_relation</code> table reference
     */
    public AuthorityMenuRelation() {
        this(DSL.name("authority_menu_relation"), null);
    }

    public <O extends Record> AuthorityMenuRelation(Table<O> child, ForeignKey<O, AuthorityMenuRelationRecord> key) {
        super(child, key, AUTHORITY_MENU_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<AuthorityMenuRelationRecord, Integer> getIdentity() {
        return (Identity<AuthorityMenuRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthorityMenuRelationRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORITY_MENU_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AuthorityMenuRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorityMenuRelationRecord>>asList(Keys.KEY_AUTHORITY_MENU_RELATION_PRIMARY);
    }

    @Override
    public AuthorityMenuRelation as(String alias) {
        return new AuthorityMenuRelation(DSL.name(alias), this);
    }

    @Override
    public AuthorityMenuRelation as(Name alias) {
        return new AuthorityMenuRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityMenuRelation rename(String name) {
        return new AuthorityMenuRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityMenuRelation rename(Name name) {
        return new AuthorityMenuRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
