/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.AuthorityFileRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-文件关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityFileRelation extends TableImpl<AuthorityFileRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.authority_file_relation</code>
     */
    public static final AuthorityFileRelation AUTHORITY_FILE_RELATION = new AuthorityFileRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorityFileRelationRecord> getRecordType() {
        return AuthorityFileRelationRecord.class;
    }

    /**
     * The column <code>idaas.authority_file_relation.id</code>. 代理主键
     */
    public final TableField<AuthorityFileRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.authority_file_relation.create_time</code>. 创建时间
     */
    public final TableField<AuthorityFileRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.authority_file_relation.modified_time</code>. 修改时间
     */
    public final TableField<AuthorityFileRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private AuthorityFileRelation(Name alias, Table<AuthorityFileRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorityFileRelation(Name alias, Table<AuthorityFileRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-文件关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.authority_file_relation</code> table reference
     */
    public AuthorityFileRelation(String alias) {
        this(DSL.name(alias), AUTHORITY_FILE_RELATION);
    }

    /**
     * Create an aliased <code>idaas.authority_file_relation</code> table reference
     */
    public AuthorityFileRelation(Name alias) {
        this(alias, AUTHORITY_FILE_RELATION);
    }

    /**
     * Create a <code>idaas.authority_file_relation</code> table reference
     */
    public AuthorityFileRelation() {
        this(DSL.name("authority_file_relation"), null);
    }

    public <O extends Record> AuthorityFileRelation(Table<O> child, ForeignKey<O, AuthorityFileRelationRecord> key) {
        super(child, key, AUTHORITY_FILE_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<AuthorityFileRelationRecord, Integer> getIdentity() {
        return (Identity<AuthorityFileRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthorityFileRelationRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORITY_FILE_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AuthorityFileRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorityFileRelationRecord>>asList(Keys.KEY_AUTHORITY_FILE_RELATION_PRIMARY);
    }

    @Override
    public AuthorityFileRelation as(String alias) {
        return new AuthorityFileRelation(DSL.name(alias), this);
    }

    @Override
    public AuthorityFileRelation as(Name alias) {
        return new AuthorityFileRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityFileRelation rename(String name) {
        return new AuthorityFileRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityFileRelation rename(Name name) {
        return new AuthorityFileRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
