/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.AuthorityPageElementRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-页面元素关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityPageElementRelation extends TableImpl<AuthorityPageElementRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.authority_page_element_relation</code>
     */
    public static final AuthorityPageElementRelation AUTHORITY_PAGE_ELEMENT_RELATION = new AuthorityPageElementRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorityPageElementRelationRecord> getRecordType() {
        return AuthorityPageElementRelationRecord.class;
    }

    /**
     * The column <code>idaas.authority_page_element_relation.id</code>. 代理主键
     */
    public final TableField<AuthorityPageElementRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.authority_page_element_relation.create_time</code>. 创建时间
     */
    public final TableField<AuthorityPageElementRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.authority_page_element_relation.modified_time</code>. 修改时间
     */
    public final TableField<AuthorityPageElementRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private AuthorityPageElementRelation(Name alias, Table<AuthorityPageElementRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorityPageElementRelation(Name alias, Table<AuthorityPageElementRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-页面元素关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.authority_page_element_relation</code> table reference
     */
    public AuthorityPageElementRelation(String alias) {
        this(DSL.name(alias), AUTHORITY_PAGE_ELEMENT_RELATION);
    }

    /**
     * Create an aliased <code>idaas.authority_page_element_relation</code> table reference
     */
    public AuthorityPageElementRelation(Name alias) {
        this(alias, AUTHORITY_PAGE_ELEMENT_RELATION);
    }

    /**
     * Create a <code>idaas.authority_page_element_relation</code> table reference
     */
    public AuthorityPageElementRelation() {
        this(DSL.name("authority_page_element_relation"), null);
    }

    public <O extends Record> AuthorityPageElementRelation(Table<O> child, ForeignKey<O, AuthorityPageElementRelationRecord> key) {
        super(child, key, AUTHORITY_PAGE_ELEMENT_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<AuthorityPageElementRelationRecord, Integer> getIdentity() {
        return (Identity<AuthorityPageElementRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthorityPageElementRelationRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORITY_PAGE_ELEMENT_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AuthorityPageElementRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorityPageElementRelationRecord>>asList(Keys.KEY_AUTHORITY_PAGE_ELEMENT_RELATION_PRIMARY);
    }

    @Override
    public AuthorityPageElementRelation as(String alias) {
        return new AuthorityPageElementRelation(DSL.name(alias), this);
    }

    @Override
    public AuthorityPageElementRelation as(Name alias) {
        return new AuthorityPageElementRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityPageElementRelation rename(String name) {
        return new AuthorityPageElementRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityPageElementRelation rename(Name name) {
        return new AuthorityPageElementRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
