/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.AuthorityApiRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 权限-API权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityApiRelation extends TableImpl<AuthorityApiRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.authority_api_relation</code>
     */
    public static final AuthorityApiRelation AUTHORITY_API_RELATION = new AuthorityApiRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorityApiRelationRecord> getRecordType() {
        return AuthorityApiRelationRecord.class;
    }

    /**
     * The column <code>idaas.authority_api_relation.id</code>. 代理主键
     */
    public final TableField<AuthorityApiRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.authority_api_relation.url</code>. Restful的API URL
     */
    public final TableField<AuthorityApiRelationRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(100).nullable(false), this, "Restful的API URL");

    /**
     * The column <code>idaas.authority_api_relation.create_time</code>. 创建时间
     */
    public final TableField<AuthorityApiRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.authority_api_relation.modified_time</code>. 修改时间
     */
    public final TableField<AuthorityApiRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private AuthorityApiRelation(Name alias, Table<AuthorityApiRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthorityApiRelation(Name alias, Table<AuthorityApiRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("权限-API权限表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.authority_api_relation</code> table reference
     */
    public AuthorityApiRelation(String alias) {
        this(DSL.name(alias), AUTHORITY_API_RELATION);
    }

    /**
     * Create an aliased <code>idaas.authority_api_relation</code> table reference
     */
    public AuthorityApiRelation(Name alias) {
        this(alias, AUTHORITY_API_RELATION);
    }

    /**
     * Create a <code>idaas.authority_api_relation</code> table reference
     */
    public AuthorityApiRelation() {
        this(DSL.name("authority_api_relation"), null);
    }

    public <O extends Record> AuthorityApiRelation(Table<O> child, ForeignKey<O, AuthorityApiRelationRecord> key) {
        super(child, key, AUTHORITY_API_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<AuthorityApiRelationRecord, Integer> getIdentity() {
        return (Identity<AuthorityApiRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthorityApiRelationRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORITY_API_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AuthorityApiRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorityApiRelationRecord>>asList(Keys.KEY_AUTHORITY_API_RELATION_PRIMARY);
    }

    @Override
    public AuthorityApiRelation as(String alias) {
        return new AuthorityApiRelation(DSL.name(alias), this);
    }

    @Override
    public AuthorityApiRelation as(Name alias) {
        return new AuthorityApiRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityApiRelation rename(String name) {
        return new AuthorityApiRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorityApiRelation rename(Name name) {
        return new AuthorityApiRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
