/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.FileAuthorityRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 文件权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileAuthority extends TableImpl<FileAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.file_authority</code>
     */
    public static final FileAuthority FILE_AUTHORITY = new FileAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileAuthorityRecord> getRecordType() {
        return FileAuthorityRecord.class;
    }

    /**
     * The column <code>idaas.file_authority.id</code>. 主键
     */
    public final TableField<FileAuthorityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>idaas.file_authority.create_time</code>. 创建时间
     */
    public final TableField<FileAuthorityRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.file_authority.modified_time</code>. 修改时间
     */
    public final TableField<FileAuthorityRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private FileAuthority(Name alias, Table<FileAuthorityRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileAuthority(Name alias, Table<FileAuthorityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("文件权限表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.file_authority</code> table reference
     */
    public FileAuthority(String alias) {
        this(DSL.name(alias), FILE_AUTHORITY);
    }

    /**
     * Create an aliased <code>idaas.file_authority</code> table reference
     */
    public FileAuthority(Name alias) {
        this(alias, FILE_AUTHORITY);
    }

    /**
     * Create a <code>idaas.file_authority</code> table reference
     */
    public FileAuthority() {
        this(DSL.name("file_authority"), null);
    }

    public <O extends Record> FileAuthority(Table<O> child, ForeignKey<O, FileAuthorityRecord> key) {
        super(child, key, FILE_AUTHORITY);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<FileAuthorityRecord, Integer> getIdentity() {
        return (Identity<FileAuthorityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FileAuthorityRecord> getPrimaryKey() {
        return Keys.KEY_FILE_AUTHORITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<FileAuthorityRecord>> getKeys() {
        return Arrays.<UniqueKey<FileAuthorityRecord>>asList(Keys.KEY_FILE_AUTHORITY_PRIMARY);
    }

    @Override
    public FileAuthority as(String alias) {
        return new FileAuthority(DSL.name(alias), this);
    }

    @Override
    public FileAuthority as(Name alias) {
        return new FileAuthority(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileAuthority rename(String name) {
        return new FileAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileAuthority rename(Name name) {
        return new FileAuthority(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
