/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.PageElementAuthorityRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 页面元素权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageElementAuthority extends TableImpl<PageElementAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.page_element_authority</code>
     */
    public static final PageElementAuthority PAGE_ELEMENT_AUTHORITY = new PageElementAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PageElementAuthorityRecord> getRecordType() {
        return PageElementAuthorityRecord.class;
    }

    /**
     * The column <code>idaas.page_element_authority.id</code>. 主键
     */
    public final TableField<PageElementAuthorityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>idaas.page_element_authority.create_time</code>. 创建时间
     */
    public final TableField<PageElementAuthorityRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.page_element_authority.modified_time</code>. 修改时间
     */
    public final TableField<PageElementAuthorityRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private PageElementAuthority(Name alias, Table<PageElementAuthorityRecord> aliased) {
        this(alias, aliased, null);
    }

    private PageElementAuthority(Name alias, Table<PageElementAuthorityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("页面元素权限表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.page_element_authority</code> table reference
     */
    public PageElementAuthority(String alias) {
        this(DSL.name(alias), PAGE_ELEMENT_AUTHORITY);
    }

    /**
     * Create an aliased <code>idaas.page_element_authority</code> table reference
     */
    public PageElementAuthority(Name alias) {
        this(alias, PAGE_ELEMENT_AUTHORITY);
    }

    /**
     * Create a <code>idaas.page_element_authority</code> table reference
     */
    public PageElementAuthority() {
        this(DSL.name("page_element_authority"), null);
    }

    public <O extends Record> PageElementAuthority(Table<O> child, ForeignKey<O, PageElementAuthorityRecord> key) {
        super(child, key, PAGE_ELEMENT_AUTHORITY);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<PageElementAuthorityRecord, Integer> getIdentity() {
        return (Identity<PageElementAuthorityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PageElementAuthorityRecord> getPrimaryKey() {
        return Keys.KEY_PAGE_ELEMENT_AUTHORITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<PageElementAuthorityRecord>> getKeys() {
        return Arrays.<UniqueKey<PageElementAuthorityRecord>>asList(Keys.KEY_PAGE_ELEMENT_AUTHORITY_PRIMARY);
    }

    @Override
    public PageElementAuthority as(String alias) {
        return new PageElementAuthority(DSL.name(alias), this);
    }

    @Override
    public PageElementAuthority as(Name alias) {
        return new PageElementAuthority(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PageElementAuthority rename(String name) {
        return new PageElementAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PageElementAuthority rename(Name name) {
        return new PageElementAuthority(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
