/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.RoleAuthorityRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 角色-权限关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleAuthorityRelation extends TableImpl<RoleAuthorityRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.role_authority_relation</code>
     */
    public static final RoleAuthorityRelation ROLE_AUTHORITY_RELATION = new RoleAuthorityRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleAuthorityRelationRecord> getRecordType() {
        return RoleAuthorityRelationRecord.class;
    }

    /**
     * The column <code>idaas.role_authority_relation.id</code>. 代理主键
     */
    public final TableField<RoleAuthorityRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.role_authority_relation.role_id</code>. 角色ID
     */
    public final TableField<RoleAuthorityRelationRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.INTEGER.nullable(false), this, "角色ID");

    /**
     * The column <code>idaas.role_authority_relation.authority_id</code>. 权限ID
     */
    public final TableField<RoleAuthorityRelationRecord, Integer> AUTHORITY_ID = createField(DSL.name("authority_id"), SQLDataType.INTEGER.nullable(false), this, "权限ID");

    /**
     * The column <code>idaas.role_authority_relation.create_time</code>. 创建时间
     */
    public final TableField<RoleAuthorityRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.role_authority_relation.modified_time</code>. 修改时间
     */
    public final TableField<RoleAuthorityRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private RoleAuthorityRelation(Name alias, Table<RoleAuthorityRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleAuthorityRelation(Name alias, Table<RoleAuthorityRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("角色-权限关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.role_authority_relation</code> table reference
     */
    public RoleAuthorityRelation(String alias) {
        this(DSL.name(alias), ROLE_AUTHORITY_RELATION);
    }

    /**
     * Create an aliased <code>idaas.role_authority_relation</code> table reference
     */
    public RoleAuthorityRelation(Name alias) {
        this(alias, ROLE_AUTHORITY_RELATION);
    }

    /**
     * Create a <code>idaas.role_authority_relation</code> table reference
     */
    public RoleAuthorityRelation() {
        this(DSL.name("role_authority_relation"), null);
    }

    public <O extends Record> RoleAuthorityRelation(Table<O> child, ForeignKey<O, RoleAuthorityRelationRecord> key) {
        super(child, key, ROLE_AUTHORITY_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<RoleAuthorityRelationRecord, Integer> getIdentity() {
        return (Identity<RoleAuthorityRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoleAuthorityRelationRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_AUTHORITY_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<RoleAuthorityRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleAuthorityRelationRecord>>asList(Keys.KEY_ROLE_AUTHORITY_RELATION_PRIMARY);
    }

    @Override
    public RoleAuthorityRelation as(String alias) {
        return new RoleAuthorityRelation(DSL.name(alias), this);
    }

    @Override
    public RoleAuthorityRelation as(Name alias) {
        return new RoleAuthorityRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleAuthorityRelation rename(String name) {
        return new RoleAuthorityRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleAuthorityRelation rename(Name name) {
        return new RoleAuthorityRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
