/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.UserUserGroupRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户-用户组关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserUserGroupRelation extends TableImpl<UserUserGroupRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.user_user_group_relation</code>
     */
    public static final UserUserGroupRelation USER_USER_GROUP_RELATION = new UserUserGroupRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserUserGroupRelationRecord> getRecordType() {
        return UserUserGroupRelationRecord.class;
    }

    /**
     * The column <code>idaas.user_user_group_relation.id</code>. 代理主键
     */
    public final TableField<UserUserGroupRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.user_user_group_relation.create_time</code>. 创建时间
     */
    public final TableField<UserUserGroupRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.user_user_group_relation.modified_time</code>. 修改时间
     */
    public final TableField<UserUserGroupRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private UserUserGroupRelation(Name alias, Table<UserUserGroupRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserUserGroupRelation(Name alias, Table<UserUserGroupRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户-用户组关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.user_user_group_relation</code> table reference
     */
    public UserUserGroupRelation(String alias) {
        this(DSL.name(alias), USER_USER_GROUP_RELATION);
    }

    /**
     * Create an aliased <code>idaas.user_user_group_relation</code> table reference
     */
    public UserUserGroupRelation(Name alias) {
        this(alias, USER_USER_GROUP_RELATION);
    }

    /**
     * Create a <code>idaas.user_user_group_relation</code> table reference
     */
    public UserUserGroupRelation() {
        this(DSL.name("user_user_group_relation"), null);
    }

    public <O extends Record> UserUserGroupRelation(Table<O> child, ForeignKey<O, UserUserGroupRelationRecord> key) {
        super(child, key, USER_USER_GROUP_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<UserUserGroupRelationRecord, Integer> getIdentity() {
        return (Identity<UserUserGroupRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserUserGroupRelationRecord> getPrimaryKey() {
        return Keys.KEY_USER_USER_GROUP_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserUserGroupRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<UserUserGroupRelationRecord>>asList(Keys.KEY_USER_USER_GROUP_RELATION_PRIMARY);
    }

    @Override
    public UserUserGroupRelation as(String alias) {
        return new UserUserGroupRelation(DSL.name(alias), this);
    }

    @Override
    public UserUserGroupRelation as(Name alias) {
        return new UserUserGroupRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserUserGroupRelation rename(String name) {
        return new UserUserGroupRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserUserGroupRelation rename(Name name) {
        return new UserUserGroupRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
