/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables;


import com.leryn.auth.data.Idaas;
import com.leryn.auth.data.Keys;
import com.leryn.auth.data.tables.records.UserGroupRoleRelationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户组-角色关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRoleRelation extends TableImpl<UserGroupRoleRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas.user_group_role_relation</code>
     */
    public static final UserGroupRoleRelation USER_GROUP_ROLE_RELATION = new UserGroupRoleRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserGroupRoleRelationRecord> getRecordType() {
        return UserGroupRoleRelationRecord.class;
    }

    /**
     * The column <code>idaas.user_group_role_relation.id</code>. 代理主键
     */
    public final TableField<UserGroupRoleRelationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "代理主键");

    /**
     * The column <code>idaas.user_group_role_relation.create_time</code>. 创建时间
     */
    public final TableField<UserGroupRoleRelationRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>idaas.user_group_role_relation.modified_time</code>. 修改时间
     */
    public final TableField<UserGroupRoleRelationRecord, LocalDateTime> MODIFIED_TIME = createField(DSL.name("modified_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "修改时间");

    private UserGroupRoleRelation(Name alias, Table<UserGroupRoleRelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserGroupRoleRelation(Name alias, Table<UserGroupRoleRelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户组-角色关系表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>idaas.user_group_role_relation</code> table reference
     */
    public UserGroupRoleRelation(String alias) {
        this(DSL.name(alias), USER_GROUP_ROLE_RELATION);
    }

    /**
     * Create an aliased <code>idaas.user_group_role_relation</code> table reference
     */
    public UserGroupRoleRelation(Name alias) {
        this(alias, USER_GROUP_ROLE_RELATION);
    }

    /**
     * Create a <code>idaas.user_group_role_relation</code> table reference
     */
    public UserGroupRoleRelation() {
        this(DSL.name("user_group_role_relation"), null);
    }

    public <O extends Record> UserGroupRoleRelation(Table<O> child, ForeignKey<O, UserGroupRoleRelationRecord> key) {
        super(child, key, USER_GROUP_ROLE_RELATION);
    }

    @Override
    public Schema getSchema() {
        return Idaas.IDAAS;
    }

    @Override
    public Identity<UserGroupRoleRelationRecord, Integer> getIdentity() {
        return (Identity<UserGroupRoleRelationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserGroupRoleRelationRecord> getPrimaryKey() {
        return Keys.KEY_USER_GROUP_ROLE_RELATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserGroupRoleRelationRecord>> getKeys() {
        return Arrays.<UniqueKey<UserGroupRoleRelationRecord>>asList(Keys.KEY_USER_GROUP_ROLE_RELATION_PRIMARY);
    }

    @Override
    public UserGroupRoleRelation as(String alias) {
        return new UserGroupRoleRelation(DSL.name(alias), this);
    }

    @Override
    public UserGroupRoleRelation as(Name alias) {
        return new UserGroupRoleRelation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroupRoleRelation rename(String name) {
        return new UserGroupRoleRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroupRoleRelation rename(Name name) {
        return new UserGroupRoleRelation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
