/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data;


import com.leryn.auth.data.tables.Api;
import com.leryn.auth.data.tables.Authority;
import com.leryn.auth.data.tables.AuthorityApiRelation;
import com.leryn.auth.data.tables.AuthorityFileRelation;
import com.leryn.auth.data.tables.AuthorityMenuRelation;
import com.leryn.auth.data.tables.AuthorityPageElementRelation;
import com.leryn.auth.data.tables.FileAuthority;
import com.leryn.auth.data.tables.MenuAuthority;
import com.leryn.auth.data.tables.PageElementAuthority;
import com.leryn.auth.data.tables.Role;
import com.leryn.auth.data.tables.RoleAuthorityRelation;
import com.leryn.auth.data.tables.User;
import com.leryn.auth.data.tables.UserGroup;
import com.leryn.auth.data.tables.UserGroupRoleRelation;
import com.leryn.auth.data.tables.UserRoleRelation;
import com.leryn.auth.data.tables.UserUserGroupRelation;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Idaas extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>idaas</code>
     */
    public static final Idaas IDAAS = new Idaas();

    /**
     * API表
     */
    public final Api API = Api.API;

    /**
     * 权限表
     */
    public final Authority AUTHORITY = Authority.AUTHORITY;

    /**
     * 权限-API权限表
     */
    public final AuthorityApiRelation AUTHORITY_API_RELATION = AuthorityApiRelation.AUTHORITY_API_RELATION;

    /**
     * 权限-文件关系表
     */
    public final AuthorityFileRelation AUTHORITY_FILE_RELATION = AuthorityFileRelation.AUTHORITY_FILE_RELATION;

    /**
     * 权限-菜单关系表
     */
    public final AuthorityMenuRelation AUTHORITY_MENU_RELATION = AuthorityMenuRelation.AUTHORITY_MENU_RELATION;

    /**
     * 权限-页面元素关系表
     */
    public final AuthorityPageElementRelation AUTHORITY_PAGE_ELEMENT_RELATION = AuthorityPageElementRelation.AUTHORITY_PAGE_ELEMENT_RELATION;

    /**
     * 文件权限表
     */
    public final FileAuthority FILE_AUTHORITY = FileAuthority.FILE_AUTHORITY;

    /**
     * 菜单权限表
     */
    public final MenuAuthority MENU_AUTHORITY = MenuAuthority.MENU_AUTHORITY;

    /**
     * 页面元素权限表
     */
    public final PageElementAuthority PAGE_ELEMENT_AUTHORITY = PageElementAuthority.PAGE_ELEMENT_AUTHORITY;

    /**
     * 角色表
     */
    public final Role ROLE = Role.ROLE;

    /**
     * 角色-权限关系表
     */
    public final RoleAuthorityRelation ROLE_AUTHORITY_RELATION = RoleAuthorityRelation.ROLE_AUTHORITY_RELATION;

    /**
     * 用户表
     */
    public final User USER = User.USER;

    /**
     * 用户组表
     */
    public final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * 用户组-角色关系表
     */
    public final UserGroupRoleRelation USER_GROUP_ROLE_RELATION = UserGroupRoleRelation.USER_GROUP_ROLE_RELATION;

    /**
     * 用户-角色关系表
     */
    public final UserRoleRelation USER_ROLE_RELATION = UserRoleRelation.USER_ROLE_RELATION;

    /**
     * 用户-用户组关系表
     */
    public final UserUserGroupRelation USER_USER_GROUP_RELATION = UserUserGroupRelation.USER_USER_GROUP_RELATION;

    /**
     * No further instances allowed
     */
    private Idaas() {
        super("idaas", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Api.API,
            Authority.AUTHORITY,
            AuthorityApiRelation.AUTHORITY_API_RELATION,
            AuthorityFileRelation.AUTHORITY_FILE_RELATION,
            AuthorityMenuRelation.AUTHORITY_MENU_RELATION,
            AuthorityPageElementRelation.AUTHORITY_PAGE_ELEMENT_RELATION,
            FileAuthority.FILE_AUTHORITY,
            MenuAuthority.MENU_AUTHORITY,
            PageElementAuthority.PAGE_ELEMENT_AUTHORITY,
            Role.ROLE,
            RoleAuthorityRelation.ROLE_AUTHORITY_RELATION,
            User.USER,
            UserGroup.USER_GROUP,
            UserGroupRoleRelation.USER_GROUP_ROLE_RELATION,
            UserRoleRelation.USER_ROLE_RELATION,
            UserUserGroupRelation.USER_USER_GROUP_RELATION);
    }
}
