/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data;


import com.leryn.auth.data.tables.Api;
import com.leryn.auth.data.tables.Authority;
import com.leryn.auth.data.tables.AuthorityApiRelation;
import com.leryn.auth.data.tables.AuthorityFileRelation;
import com.leryn.auth.data.tables.AuthorityMenuRelation;
import com.leryn.auth.data.tables.AuthorityPageElementRelation;
import com.leryn.auth.data.tables.FileAuthority;
import com.leryn.auth.data.tables.MenuAuthority;
import com.leryn.auth.data.tables.PageElementAuthority;
import com.leryn.auth.data.tables.Role;
import com.leryn.auth.data.tables.RoleAuthorityRelation;
import com.leryn.auth.data.tables.User;
import com.leryn.auth.data.tables.UserGroup;
import com.leryn.auth.data.tables.UserGroupRoleRelation;
import com.leryn.auth.data.tables.UserRoleRelation;
import com.leryn.auth.data.tables.UserUserGroupRelation;


/**
 * Convenience access to all tables in idaas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * API表
     */
    public static final Api API = Api.API;

    /**
     * 权限表
     */
    public static final Authority AUTHORITY = Authority.AUTHORITY;

    /**
     * 权限-API权限表
     */
    public static final AuthorityApiRelation AUTHORITY_API_RELATION = AuthorityApiRelation.AUTHORITY_API_RELATION;

    /**
     * 权限-文件关系表
     */
    public static final AuthorityFileRelation AUTHORITY_FILE_RELATION = AuthorityFileRelation.AUTHORITY_FILE_RELATION;

    /**
     * 权限-菜单关系表
     */
    public static final AuthorityMenuRelation AUTHORITY_MENU_RELATION = AuthorityMenuRelation.AUTHORITY_MENU_RELATION;

    /**
     * 权限-页面元素关系表
     */
    public static final AuthorityPageElementRelation AUTHORITY_PAGE_ELEMENT_RELATION = AuthorityPageElementRelation.AUTHORITY_PAGE_ELEMENT_RELATION;

    /**
     * 文件权限表
     */
    public static final FileAuthority FILE_AUTHORITY = FileAuthority.FILE_AUTHORITY;

    /**
     * 菜单权限表
     */
    public static final MenuAuthority MENU_AUTHORITY = MenuAuthority.MENU_AUTHORITY;

    /**
     * 页面元素权限表
     */
    public static final PageElementAuthority PAGE_ELEMENT_AUTHORITY = PageElementAuthority.PAGE_ELEMENT_AUTHORITY;

    /**
     * 角色表
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * 角色-权限关系表
     */
    public static final RoleAuthorityRelation ROLE_AUTHORITY_RELATION = RoleAuthorityRelation.ROLE_AUTHORITY_RELATION;

    /**
     * 用户表
     */
    public static final User USER = User.USER;

    /**
     * 用户组表
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * 用户组-角色关系表
     */
    public static final UserGroupRoleRelation USER_GROUP_ROLE_RELATION = UserGroupRoleRelation.USER_GROUP_ROLE_RELATION;

    /**
     * 用户-角色关系表
     */
    public static final UserRoleRelation USER_ROLE_RELATION = UserRoleRelation.USER_ROLE_RELATION;

    /**
     * 用户-用户组关系表
     */
    public static final UserUserGroupRelation USER_USER_GROUP_RELATION = UserUserGroupRelation.USER_USER_GROUP_RELATION;
}
