/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.records;


import com.leryn.gateway.data.tables.Dictionary;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * 字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictionaryRecord extends TableRecordImpl<DictionaryRecord> implements Record7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gateway.dictionary.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gateway.dictionary.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gateway.dictionary.entry_key</code>. 词条名
     */
    public void setEntryKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gateway.dictionary.entry_key</code>. 词条名
     */
    public String getEntryKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gateway.dictionary.entry_value</code>. 词条值
     */
    public void setEntryValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gateway.dictionary.entry_value</code>. 词条值
     */
    public String getEntryValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gateway.dictionary.type</code>. 类型
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gateway.dictionary.type</code>. 类型
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gateway.dictionary.description</code>. 描述
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gateway.dictionary.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gateway.dictionary.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>gateway.dictionary.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>gateway.dictionary.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>gateway.dictionary.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Dictionary.DICTIONARY.ID;
    }

    @Override
    public Field<String> field2() {
        return Dictionary.DICTIONARY.ENTRY_KEY;
    }

    @Override
    public Field<String> field3() {
        return Dictionary.DICTIONARY.ENTRY_VALUE;
    }

    @Override
    public Field<String> field4() {
        return Dictionary.DICTIONARY.TYPE;
    }

    @Override
    public Field<String> field5() {
        return Dictionary.DICTIONARY.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Dictionary.DICTIONARY.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Dictionary.DICTIONARY.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEntryKey();
    }

    @Override
    public String component3() {
        return getEntryValue();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEntryKey();
    }

    @Override
    public String value3() {
        return getEntryValue();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateTime();
    }

    @Override
    public DictionaryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DictionaryRecord value2(String value) {
        setEntryKey(value);
        return this;
    }

    @Override
    public DictionaryRecord value3(String value) {
        setEntryValue(value);
        return this;
    }

    @Override
    public DictionaryRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public DictionaryRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DictionaryRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public DictionaryRecord value7(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public DictionaryRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictionaryRecord
     */
    public DictionaryRecord() {
        super(Dictionary.DICTIONARY);
    }

    /**
     * Create a detached, initialised DictionaryRecord
     */
    public DictionaryRecord(Integer id, String entryKey, String entryValue, String type, String description, LocalDateTime createTime, LocalDateTime updateTime) {
        super(Dictionary.DICTIONARY);

        setId(id);
        setEntryKey(entryKey);
        setEntryValue(entryValue);
        setType(type);
        setDescription(description);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
