/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.records;


import com.leryn.gateway.data.tables.ServiceDiscovery;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 服务发现
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceDiscoveryRecord extends UpdatableRecordImpl<ServiceDiscoveryRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gateway.service_discovery.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gateway.service_discovery.service</code>. 服务名
     */
    public void setService(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.service</code>. 服务名
     */
    public String getService() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gateway.service_discovery.host</code>. 主机Host
     */
    public void setHost(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.host</code>. 主机Host
     */
    public String getHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gateway.service_discovery.profile</code>. 环境, profile
     */
    public void setProfile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.profile</code>. 环境, profile
     */
    public String getProfile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gateway.service_discovery.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>gateway.service_discovery.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>gateway.service_discovery.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ServiceDiscovery.SERVICE_DISCOVERY.ID;
    }

    @Override
    public Field<String> field2() {
        return ServiceDiscovery.SERVICE_DISCOVERY.SERVICE;
    }

    @Override
    public Field<String> field3() {
        return ServiceDiscovery.SERVICE_DISCOVERY.HOST;
    }

    @Override
    public Field<String> field4() {
        return ServiceDiscovery.SERVICE_DISCOVERY.PROFILE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ServiceDiscovery.SERVICE_DISCOVERY.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ServiceDiscovery.SERVICE_DISCOVERY.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getService();
    }

    @Override
    public String component3() {
        return getHost();
    }

    @Override
    public String component4() {
        return getProfile();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getService();
    }

    @Override
    public String value3() {
        return getHost();
    }

    @Override
    public String value4() {
        return getProfile();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifiedTime();
    }

    @Override
    public ServiceDiscoveryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord value2(String value) {
        setService(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord value3(String value) {
        setHost(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord value4(String value) {
        setProfile(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord value6(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public ServiceDiscoveryRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceDiscoveryRecord
     */
    public ServiceDiscoveryRecord() {
        super(ServiceDiscovery.SERVICE_DISCOVERY);
    }

    /**
     * Create a detached, initialised ServiceDiscoveryRecord
     */
    public ServiceDiscoveryRecord(Integer id, String service, String host, String profile, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(ServiceDiscovery.SERVICE_DISCOVERY);

        setId(id);
        setService(service);
        setHost(host);
        setProfile(profile);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
