/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dictionary implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        entryKey;
    private String        entryValue;
    private String        type;
    private String        description;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Dictionary() {}

    public Dictionary(Dictionary value) {
        this.id = value.id;
        this.entryKey = value.entryKey;
        this.entryValue = value.entryValue;
        this.type = value.type;
        this.description = value.description;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Dictionary(
        Integer       id,
        String        entryKey,
        String        entryValue,
        String        type,
        String        description,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.entryKey = entryKey;
        this.entryValue = entryValue;
        this.type = type;
        this.description = description;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>gateway.dictionary.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gateway.dictionary.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gateway.dictionary.entry_key</code>. 词条名
     */
    public String getEntryKey() {
        return this.entryKey;
    }

    /**
     * Setter for <code>gateway.dictionary.entry_key</code>. 词条名
     */
    public void setEntryKey(String entryKey) {
        this.entryKey = entryKey;
    }

    /**
     * Getter for <code>gateway.dictionary.entry_value</code>. 词条值
     */
    public String getEntryValue() {
        return this.entryValue;
    }

    /**
     * Setter for <code>gateway.dictionary.entry_value</code>. 词条值
     */
    public void setEntryValue(String entryValue) {
        this.entryValue = entryValue;
    }

    /**
     * Getter for <code>gateway.dictionary.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>gateway.dictionary.type</code>. 类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>gateway.dictionary.description</code>. 描述
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>gateway.dictionary.description</code>. 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>gateway.dictionary.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>gateway.dictionary.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>gateway.dictionary.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>gateway.dictionary.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dictionary (");

        sb.append(id);
        sb.append(", ").append(entryKey);
        sb.append(", ").append(entryValue);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
