/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 路由表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouterTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        routerId;
    private String        urlPrefix;
    private String        routeHost;
    private Boolean       rewrite;
    private String        rewriteRegexp;
    private String        rewriteTarget;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public RouterTable() {}

    public RouterTable(RouterTable value) {
        this.id = value.id;
        this.routerId = value.routerId;
        this.urlPrefix = value.urlPrefix;
        this.routeHost = value.routeHost;
        this.rewrite = value.rewrite;
        this.rewriteRegexp = value.rewriteRegexp;
        this.rewriteTarget = value.rewriteTarget;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public RouterTable(
        Integer       id,
        String        routerId,
        String        urlPrefix,
        String        routeHost,
        Boolean       rewrite,
        String        rewriteRegexp,
        String        rewriteTarget,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.routerId = routerId;
        this.urlPrefix = urlPrefix;
        this.routeHost = routeHost;
        this.rewrite = rewrite;
        this.rewriteRegexp = rewriteRegexp;
        this.rewriteTarget = rewriteTarget;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>gateway.router_table.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gateway.router_table.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gateway.router_table.router_id</code>. 路由ID
     */
    public String getRouterId() {
        return this.routerId;
    }

    /**
     * Setter for <code>gateway.router_table.router_id</code>. 路由ID
     */
    public void setRouterId(String routerId) {
        this.routerId = routerId;
    }

    /**
     * Getter for <code>gateway.router_table.url_prefix</code>. URL前缀
     */
    public String getUrlPrefix() {
        return this.urlPrefix;
    }

    /**
     * Setter for <code>gateway.router_table.url_prefix</code>. URL前缀
     */
    public void setUrlPrefix(String urlPrefix) {
        this.urlPrefix = urlPrefix;
    }

    /**
     * Getter for <code>gateway.router_table.route_host</code>. 路由地址
     */
    public String getRouteHost() {
        return this.routeHost;
    }

    /**
     * Setter for <code>gateway.router_table.route_host</code>. 路由地址
     */
    public void setRouteHost(String routeHost) {
        this.routeHost = routeHost;
    }

    /**
     * Getter for <code>gateway.router_table.rewrite</code>. 是否重写URL路径
     */
    public Boolean getRewrite() {
        return this.rewrite;
    }

    /**
     * Setter for <code>gateway.router_table.rewrite</code>. 是否重写URL路径
     */
    public void setRewrite(Boolean rewrite) {
        this.rewrite = rewrite;
    }

    /**
     * Getter for <code>gateway.router_table.rewrite_regexp</code>. 重写表达式
     */
    public String getRewriteRegexp() {
        return this.rewriteRegexp;
    }

    /**
     * Setter for <code>gateway.router_table.rewrite_regexp</code>. 重写表达式
     */
    public void setRewriteRegexp(String rewriteRegexp) {
        this.rewriteRegexp = rewriteRegexp;
    }

    /**
     * Getter for <code>gateway.router_table.rewrite_target</code>. 重写表达式
     */
    public String getRewriteTarget() {
        return this.rewriteTarget;
    }

    /**
     * Setter for <code>gateway.router_table.rewrite_target</code>. 重写表达式
     */
    public void setRewriteTarget(String rewriteTarget) {
        this.rewriteTarget = rewriteTarget;
    }

    /**
     * Getter for <code>gateway.router_table.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>gateway.router_table.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>gateway.router_table.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>gateway.router_table.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RouterTable (");

        sb.append(id);
        sb.append(", ").append(routerId);
        sb.append(", ").append(urlPrefix);
        sb.append(", ").append(routeHost);
        sb.append(", ").append(rewrite);
        sb.append(", ").append(rewriteRegexp);
        sb.append(", ").append(rewriteTarget);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
