/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 服务发现
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceDiscovery implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        service;
    private String        host;
    private String        profile;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public ServiceDiscovery() {}

    public ServiceDiscovery(ServiceDiscovery value) {
        this.id = value.id;
        this.service = value.service;
        this.host = value.host;
        this.profile = value.profile;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public ServiceDiscovery(
        Integer       id,
        String        service,
        String        host,
        String        profile,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.service = service;
        this.host = host;
        this.profile = profile;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>gateway.service_discovery.id</code>. 代理主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>gateway.service_discovery.id</code>. 代理主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>gateway.service_discovery.service</code>. 服务名
     */
    public String getService() {
        return this.service;
    }

    /**
     * Setter for <code>gateway.service_discovery.service</code>. 服务名
     */
    public void setService(String service) {
        this.service = service;
    }

    /**
     * Getter for <code>gateway.service_discovery.host</code>. 主机Host
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Setter for <code>gateway.service_discovery.host</code>. 主机Host
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for <code>gateway.service_discovery.profile</code>. 环境, profile
     */
    public String getProfile() {
        return this.profile;
    }

    /**
     * Setter for <code>gateway.service_discovery.profile</code>. 环境, profile
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * Getter for <code>gateway.service_discovery.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>gateway.service_discovery.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>gateway.service_discovery.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>gateway.service_discovery.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ServiceDiscovery (");

        sb.append(id);
        sb.append(", ").append(service);
        sb.append(", ").append(host);
        sb.append(", ").append(profile);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
