/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.daos;


import com.leryn.auth.data.tables.AuthorityFileRelation;
import com.leryn.auth.data.tables.records.AuthorityFileRelationRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限-文件关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AuthorityFileRelationDao extends DAOImpl<AuthorityFileRelationRecord, com.leryn.auth.data.tables.pojos.AuthorityFileRelation, Integer> {

    /**
     * Create a new AuthorityFileRelationDao without any configuration
     */
    public AuthorityFileRelationDao() {
        super(AuthorityFileRelation.AUTHORITY_FILE_RELATION, com.leryn.auth.data.tables.pojos.AuthorityFileRelation.class);
    }

    /**
     * Create a new AuthorityFileRelationDao with an attached configuration
     */
    @Autowired
    public AuthorityFileRelationDao(Configuration configuration) {
        super(AuthorityFileRelation.AUTHORITY_FILE_RELATION, com.leryn.auth.data.tables.pojos.AuthorityFileRelation.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.auth.data.tables.pojos.AuthorityFileRelation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AuthorityFileRelation.AUTHORITY_FILE_RELATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchById(Integer... values) {
        return fetch(AuthorityFileRelation.AUTHORITY_FILE_RELATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.auth.data.tables.pojos.AuthorityFileRelation fetchOneById(Integer value) {
        return fetchOne(AuthorityFileRelation.AUTHORITY_FILE_RELATION.ID, value);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AuthorityFileRelation.AUTHORITY_FILE_RELATION.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchByCreateTime(LocalDateTime... values) {
        return fetch(AuthorityFileRelation.AUTHORITY_FILE_RELATION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AuthorityFileRelation.AUTHORITY_FILE_RELATION.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.AuthorityFileRelation> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(AuthorityFileRelation.AUTHORITY_FILE_RELATION.MODIFIED_TIME, values);
    }
}
