/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.daos;


import com.leryn.auth.data.tables.Authority;
import com.leryn.auth.data.tables.records.AuthorityRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AuthorityDao extends DAOImpl<AuthorityRecord, com.leryn.auth.data.tables.pojos.Authority, Integer> {

    /**
     * Create a new AuthorityDao without any configuration
     */
    public AuthorityDao() {
        super(Authority.AUTHORITY, com.leryn.auth.data.tables.pojos.Authority.class);
    }

    /**
     * Create a new AuthorityDao with an attached configuration
     */
    @Autowired
    public AuthorityDao(Configuration configuration) {
        super(Authority.AUTHORITY, com.leryn.auth.data.tables.pojos.Authority.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.auth.data.tables.pojos.Authority object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Authority.AUTHORITY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchById(Integer... values) {
        return fetch(Authority.AUTHORITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.auth.data.tables.pojos.Authority fetchOneById(Integer value) {
        return fetchOne(Authority.AUTHORITY.ID, value);
    }

    /**
     * Fetch records that have <code>authority_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchRangeOfAuthorityId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Authority.AUTHORITY.AUTHORITY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>authority_id IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchByAuthorityId(Integer... values) {
        return fetch(Authority.AUTHORITY.AUTHORITY_ID, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Authority.AUTHORITY.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchByName(String... values) {
        return fetch(Authority.AUTHORITY.NAME, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Authority.AUTHORITY.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Authority.AUTHORITY.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Authority.AUTHORITY.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.Authority> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(Authority.AUTHORITY.MODIFIED_TIME, values);
    }
}
