/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.daos;


import com.leryn.auth.data.tables.UserGroupRoleRelation;
import com.leryn.auth.data.tables.records.UserGroupRoleRelationRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 用户组-角色关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserGroupRoleRelationDao extends DAOImpl<UserGroupRoleRelationRecord, com.leryn.auth.data.tables.pojos.UserGroupRoleRelation, Integer> {

    /**
     * Create a new UserGroupRoleRelationDao without any configuration
     */
    public UserGroupRoleRelationDao() {
        super(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION, com.leryn.auth.data.tables.pojos.UserGroupRoleRelation.class);
    }

    /**
     * Create a new UserGroupRoleRelationDao with an attached configuration
     */
    @Autowired
    public UserGroupRoleRelationDao(Configuration configuration) {
        super(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION, com.leryn.auth.data.tables.pojos.UserGroupRoleRelation.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.auth.data.tables.pojos.UserGroupRoleRelation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchById(Integer... values) {
        return fetch(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.auth.data.tables.pojos.UserGroupRoleRelation fetchOneById(Integer value) {
        return fetchOne(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.ID, value);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchByCreateTime(LocalDateTime... values) {
        return fetch(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.auth.data.tables.pojos.UserGroupRoleRelation> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(UserGroupRoleRelation.USER_GROUP_ROLE_RELATION.MODIFIED_TIME, values);
    }
}
