/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.Authority;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityRecord extends UpdatableRecordImpl<AuthorityRecord> implements Record5<Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.authority.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.authority.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.authority.authority_id</code>. 权限ID
     */
    public void setAuthorityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.authority.authority_id</code>. 权限ID
     */
    public Integer getAuthorityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>idaas.authority.name</code>. 权限名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.authority.name</code>. 权限名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>idaas.authority.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>idaas.authority.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>idaas.authority.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>idaas.authority.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Authority.AUTHORITY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Authority.AUTHORITY.AUTHORITY_ID;
    }

    @Override
    public Field<String> field3() {
        return Authority.AUTHORITY.NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Authority.AUTHORITY.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Authority.AUTHORITY.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAuthorityId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAuthorityId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedTime();
    }

    @Override
    public AuthorityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthorityRecord value2(Integer value) {
        setAuthorityId(value);
        return this;
    }

    @Override
    public AuthorityRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthorityRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuthorityRecord value5(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public AuthorityRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorityRecord
     */
    public AuthorityRecord() {
        super(Authority.AUTHORITY);
    }

    /**
     * Create a detached, initialised AuthorityRecord
     */
    public AuthorityRecord(Integer id, Integer authorityId, String name, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(Authority.AUTHORITY);

        setId(id);
        setAuthorityId(authorityId);
        setName(name);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
