/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.AuthorityApiRelation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 权限-API权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityApiRelationRecord extends UpdatableRecordImpl<AuthorityApiRelationRecord> implements Record4<Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.authority_api_relation.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.authority_api_relation.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.authority_api_relation.url</code>. Restful的API URL
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.authority_api_relation.url</code>. Restful的API URL
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>idaas.authority_api_relation.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.authority_api_relation.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>idaas.authority_api_relation.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>idaas.authority_api_relation.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthorityApiRelation.AUTHORITY_API_RELATION.ID;
    }

    @Override
    public Field<String> field2() {
        return AuthorityApiRelation.AUTHORITY_API_RELATION.URL;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return AuthorityApiRelation.AUTHORITY_API_RELATION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return AuthorityApiRelation.AUTHORITY_API_RELATION.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component4() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value4() {
        return getModifiedTime();
    }

    @Override
    public AuthorityApiRelationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthorityApiRelationRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public AuthorityApiRelationRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuthorityApiRelationRecord value4(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public AuthorityApiRelationRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorityApiRelationRecord
     */
    public AuthorityApiRelationRecord() {
        super(AuthorityApiRelation.AUTHORITY_API_RELATION);
    }

    /**
     * Create a detached, initialised AuthorityApiRelationRecord
     */
    public AuthorityApiRelationRecord(Integer id, String url, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(AuthorityApiRelation.AUTHORITY_API_RELATION);

        setId(id);
        setUrl(url);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
