/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.PageElementAuthority;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 页面元素权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageElementAuthorityRecord extends UpdatableRecordImpl<PageElementAuthorityRecord> implements Record3<Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.page_element_authority.id</code>. 主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.page_element_authority.id</code>. 主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.page_element_authority.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.page_element_authority.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>idaas.page_element_authority.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.page_element_authority.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PageElementAuthority.PAGE_ELEMENT_AUTHORITY.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return PageElementAuthority.PAGE_ELEMENT_AUTHORITY.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PageElementAuthority.PAGE_ELEMENT_AUTHORITY.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component3() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value3() {
        return getModifiedTime();
    }

    @Override
    public PageElementAuthorityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PageElementAuthorityRecord value2(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PageElementAuthorityRecord value3(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public PageElementAuthorityRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageElementAuthorityRecord
     */
    public PageElementAuthorityRecord() {
        super(PageElementAuthority.PAGE_ELEMENT_AUTHORITY);
    }

    /**
     * Create a detached, initialised PageElementAuthorityRecord
     */
    public PageElementAuthorityRecord(Integer id, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(PageElementAuthority.PAGE_ELEMENT_AUTHORITY);

        setId(id);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
