/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.RoleAuthorityRelation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色-权限关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleAuthorityRelationRecord extends UpdatableRecordImpl<RoleAuthorityRelationRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.role_authority_relation.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.role_authority_relation.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.role_authority_relation.role_id</code>. 角色ID
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.role_authority_relation.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>idaas.role_authority_relation.authority_id</code>. 权限ID
     */
    public void setAuthorityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.role_authority_relation.authority_id</code>. 权限ID
     */
    public Integer getAuthorityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>idaas.role_authority_relation.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>idaas.role_authority_relation.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>idaas.role_authority_relation.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>idaas.role_authority_relation.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RoleAuthorityRelation.ROLE_AUTHORITY_RELATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return RoleAuthorityRelation.ROLE_AUTHORITY_RELATION.ROLE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return RoleAuthorityRelation.ROLE_AUTHORITY_RELATION.AUTHORITY_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return RoleAuthorityRelation.ROLE_AUTHORITY_RELATION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return RoleAuthorityRelation.ROLE_AUTHORITY_RELATION.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public Integer component3() {
        return getAuthorityId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public Integer value3() {
        return getAuthorityId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedTime();
    }

    @Override
    public RoleAuthorityRelationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RoleAuthorityRelationRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RoleAuthorityRelationRecord value3(Integer value) {
        setAuthorityId(value);
        return this;
    }

    @Override
    public RoleAuthorityRelationRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public RoleAuthorityRelationRecord value5(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public RoleAuthorityRelationRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleAuthorityRelationRecord
     */
    public RoleAuthorityRelationRecord() {
        super(RoleAuthorityRelation.ROLE_AUTHORITY_RELATION);
    }

    /**
     * Create a detached, initialised RoleAuthorityRelationRecord
     */
    public RoleAuthorityRelationRecord(Integer id, Integer roleId, Integer authorityId, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(RoleAuthorityRelation.ROLE_AUTHORITY_RELATION);

        setId(id);
        setRoleId(roleId);
        setAuthorityId(authorityId);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
