/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.UserGroup;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户组表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupRecord extends UpdatableRecordImpl<UserGroupRecord> implements Record5<Integer, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.user_group.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.user_group.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.user_group.name</code>. 用户组名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.user_group.name</code>. 用户组名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>idaas.user_group.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.user_group.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>idaas.user_group.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>idaas.user_group.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>idaas.user_group.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>idaas.user_group.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserGroup.USER_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return UserGroup.USER_GROUP.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return UserGroup.USER_GROUP.PARENT_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserGroup.USER_GROUP.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserGroup.USER_GROUP.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getParentId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getParentId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedTime();
    }

    @Override
    public UserGroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserGroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserGroupRecord value3(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public UserGroupRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserGroupRecord value5(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public UserGroupRecord values(Integer value1, String value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupRecord
     */
    public UserGroupRecord() {
        super(UserGroup.USER_GROUP);
    }

    /**
     * Create a detached, initialised UserGroupRecord
     */
    public UserGroupRecord(Integer id, String name, Integer parentId, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(UserGroup.USER_GROUP);

        setId(id);
        setName(name);
        setParentId(parentId);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
