/*
 * This file is generated by jOOQ.
 */
package com.leryn.auth.data.tables.records;


import com.leryn.auth.data.tables.UserRoleRelation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * 用户-角色关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRelationRecord extends TableRecordImpl<UserRoleRelationRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idaas.user_role_relation.id</code>. 代理主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>idaas.user_role_relation.id</code>. 代理主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>idaas.user_role_relation.user_id</code>. 用户ID(员工号)
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>idaas.user_role_relation.user_id</code>. 用户ID(员工号)
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>idaas.user_role_relation.role_id</code>. 角色ID
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>idaas.user_role_relation.role_id</code>. 角色ID
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>idaas.user_role_relation.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>idaas.user_role_relation.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>idaas.user_role_relation.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>idaas.user_role_relation.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserRoleRelation.USER_ROLE_RELATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserRoleRelation.USER_ROLE_RELATION.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return UserRoleRelation.USER_ROLE_RELATION.ROLE_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserRoleRelation.USER_ROLE_RELATION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserRoleRelation.USER_ROLE_RELATION.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public UserRoleRelationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRoleRelationRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserRoleRelationRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public UserRoleRelationRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserRoleRelationRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public UserRoleRelationRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRelationRecord
     */
    public UserRoleRelationRecord() {
        super(UserRoleRelation.USER_ROLE_RELATION);
    }

    /**
     * Create a detached, initialised UserRoleRelationRecord
     */
    public UserRoleRelationRecord(Integer id, Integer userId, Integer roleId, LocalDateTime createTime, LocalDateTime updateTime) {
        super(UserRoleRelation.USER_ROLE_RELATION);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
