/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data;


import com.leryn.gateway.data.tables.Dictionary;
import com.leryn.gateway.data.tables.IgnoredUrl;
import com.leryn.gateway.data.tables.RouterTable;
import com.leryn.gateway.data.tables.ServiceDiscovery;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gateway extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gateway</code>
     */
    public static final Gateway GATEWAY = new Gateway();

    /**
     * 字典表
     */
    public final Dictionary DICTIONARY = Dictionary.DICTIONARY;

    /**
     * 忽略认证而放行URL路径
     */
    public final IgnoredUrl IGNORED_URL = IgnoredUrl.IGNORED_URL;

    /**
     * 路由表
     */
    public final RouterTable ROUTER_TABLE = RouterTable.ROUTER_TABLE;

    /**
     * 服务发现
     */
    public final ServiceDiscovery SERVICE_DISCOVERY = ServiceDiscovery.SERVICE_DISCOVERY;

    /**
     * No further instances allowed
     */
    private Gateway() {
        super("gateway", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Dictionary.DICTIONARY,
            IgnoredUrl.IGNORED_URL,
            RouterTable.ROUTER_TABLE,
            ServiceDiscovery.SERVICE_DISCOVERY);
    }
}
