/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data;


import com.leryn.gateway.data.tables.RouterTable;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gateway extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gateway</code>
     */
    public static final Gateway GATEWAY = new Gateway();

    /**
     * 路由表
     */
    public final RouterTable ROUTER_TABLE = RouterTable.ROUTER_TABLE;

    /**
     * No further instances allowed
     */
    private Gateway() {
        super("gateway", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            RouterTable.ROUTER_TABLE);
    }
}
