/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data;


import com.leryn.gateway.data.tables.RouterTable;
import com.leryn.gateway.data.tables.records.RouterTableRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * gateway.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RouterTableRecord> KEY_ROUTER_TABLE_PRIMARY = Internal.createUniqueKey(RouterTable.ROUTER_TABLE, DSL.name("KEY_router_table_PRIMARY"), new TableField[] { RouterTable.ROUTER_TABLE.ID }, true);
    public static final UniqueKey<RouterTableRecord> KEY_ROUTER_TABLE_ROUTER_UN = Internal.createUniqueKey(RouterTable.ROUTER_TABLE, DSL.name("KEY_router_table_router_UN"), new TableField[] { RouterTable.ROUTER_TABLE.ROUTER_ID }, true);
}
