/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data;


import com.leryn.gateway.data.tables.RouterTable;


/**
 * Convenience access to all tables in gateway.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 路由表
     */
    public static final RouterTable ROUTER_TABLE = RouterTable.ROUTER_TABLE;
}
