/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.daos;


import com.leryn.gateway.data.tables.IgnoredUrl;
import com.leryn.gateway.data.tables.records.IgnoredUrlRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 忽略认证而放行URL路径
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class IgnoredUrlDao extends DAOImpl<IgnoredUrlRecord, com.leryn.gateway.data.tables.pojos.IgnoredUrl, Integer> {

    /**
     * Create a new IgnoredUrlDao without any configuration
     */
    public IgnoredUrlDao() {
        super(IgnoredUrl.IGNORED_URL, com.leryn.gateway.data.tables.pojos.IgnoredUrl.class);
    }

    /**
     * Create a new IgnoredUrlDao with an attached configuration
     */
    @Autowired
    public IgnoredUrlDao(Configuration configuration) {
        super(IgnoredUrl.IGNORED_URL, com.leryn.gateway.data.tables.pojos.IgnoredUrl.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.gateway.data.tables.pojos.IgnoredUrl object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(IgnoredUrl.IGNORED_URL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchById(Integer... values) {
        return fetch(IgnoredUrl.IGNORED_URL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.gateway.data.tables.pojos.IgnoredUrl fetchOneById(Integer value) {
        return fetchOne(IgnoredUrl.IGNORED_URL.ID, value);
    }

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchRangeOfUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(IgnoredUrl.IGNORED_URL.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchByUrl(String... values) {
        return fetch(IgnoredUrl.IGNORED_URL.URL, values);
    }

    /**
     * Fetch a unique record that has <code>url = value</code>
     */
    public com.leryn.gateway.data.tables.pojos.IgnoredUrl fetchOneByUrl(String value) {
        return fetchOne(IgnoredUrl.IGNORED_URL.URL, value);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(IgnoredUrl.IGNORED_URL.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchByCreateTime(LocalDateTime... values) {
        return fetch(IgnoredUrl.IGNORED_URL.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(IgnoredUrl.IGNORED_URL.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.IgnoredUrl> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(IgnoredUrl.IGNORED_URL.MODIFIED_TIME, values);
    }
}
