/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.daos;


import com.leryn.gateway.data.tables.RouterTable;
import com.leryn.gateway.data.tables.records.RouterTableRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 路由表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RouterTableDao extends DAOImpl<RouterTableRecord, com.leryn.gateway.data.tables.pojos.RouterTable, Integer> {

    /**
     * Create a new RouterTableDao without any configuration
     */
    public RouterTableDao() {
        super(RouterTable.ROUTER_TABLE, com.leryn.gateway.data.tables.pojos.RouterTable.class);
    }

    /**
     * Create a new RouterTableDao with an attached configuration
     */
    @Autowired
    public RouterTableDao(Configuration configuration) {
        super(RouterTable.ROUTER_TABLE, com.leryn.gateway.data.tables.pojos.RouterTable.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.gateway.data.tables.pojos.RouterTable object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchById(Integer... values) {
        return fetch(RouterTable.ROUTER_TABLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.gateway.data.tables.pojos.RouterTable fetchOneById(Integer value) {
        return fetchOne(RouterTable.ROUTER_TABLE.ID, value);
    }

    /**
     * Fetch records that have <code>router_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfRouterId(String lowerInclusive, String upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.ROUTER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>router_id IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByRouterId(String... values) {
        return fetch(RouterTable.ROUTER_TABLE.ROUTER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>router_id = value</code>
     */
    public com.leryn.gateway.data.tables.pojos.RouterTable fetchOneByRouterId(String value) {
        return fetchOne(RouterTable.ROUTER_TABLE.ROUTER_ID, value);
    }

    /**
     * Fetch records that have <code>url_prefix BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfUrlPrefix(String lowerInclusive, String upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.URL_PREFIX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url_prefix IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByUrlPrefix(String... values) {
        return fetch(RouterTable.ROUTER_TABLE.URL_PREFIX, values);
    }

    /**
     * Fetch records that have <code>route_host BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfRouteHost(String lowerInclusive, String upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.ROUTE_HOST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>route_host IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByRouteHost(String... values) {
        return fetch(RouterTable.ROUTER_TABLE.ROUTE_HOST, values);
    }

    /**
     * Fetch records that have <code>rewrite BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfRewrite(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.REWRITE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rewrite IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByRewrite(Boolean... values) {
        return fetch(RouterTable.ROUTER_TABLE.REWRITE, values);
    }

    /**
     * Fetch records that have <code>rewrite_regexp BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfRewriteRegexp(String lowerInclusive, String upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.REWRITE_REGEXP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rewrite_regexp IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByRewriteRegexp(String... values) {
        return fetch(RouterTable.ROUTER_TABLE.REWRITE_REGEXP, values);
    }

    /**
     * Fetch records that have <code>rewrite_target BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfRewriteTarget(String lowerInclusive, String upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.REWRITE_TARGET, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rewrite_target IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByRewriteTarget(String... values) {
        return fetch(RouterTable.ROUTER_TABLE.REWRITE_TARGET, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByCreateTime(LocalDateTime... values) {
        return fetch(RouterTable.ROUTER_TABLE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(RouterTable.ROUTER_TABLE.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.RouterTable> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(RouterTable.ROUTER_TABLE.MODIFIED_TIME, values);
    }
}
