/*
 * This file is generated by jOOQ.
 */
package com.leryn.gateway.data.tables.daos;


import com.leryn.gateway.data.tables.ServiceDiscovery;
import com.leryn.gateway.data.tables.records.ServiceDiscoveryRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 服务发现
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ServiceDiscoveryDao extends DAOImpl<ServiceDiscoveryRecord, com.leryn.gateway.data.tables.pojos.ServiceDiscovery, Integer> {

    /**
     * Create a new ServiceDiscoveryDao without any configuration
     */
    public ServiceDiscoveryDao() {
        super(ServiceDiscovery.SERVICE_DISCOVERY, com.leryn.gateway.data.tables.pojos.ServiceDiscovery.class);
    }

    /**
     * Create a new ServiceDiscoveryDao with an attached configuration
     */
    @Autowired
    public ServiceDiscoveryDao(Configuration configuration) {
        super(ServiceDiscovery.SERVICE_DISCOVERY, com.leryn.gateway.data.tables.pojos.ServiceDiscovery.class, configuration);
    }

    @Override
    public Integer getId(com.leryn.gateway.data.tables.pojos.ServiceDiscovery object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchById(Integer... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.leryn.gateway.data.tables.pojos.ServiceDiscovery fetchOneById(Integer value) {
        return fetchOne(ServiceDiscovery.SERVICE_DISCOVERY.ID, value);
    }

    /**
     * Fetch records that have <code>service BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfService(String lowerInclusive, String upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.SERVICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>service IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchByService(String... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.SERVICE, values);
    }

    /**
     * Fetch records that have <code>host BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfHost(String lowerInclusive, String upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.HOST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>host IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchByHost(String... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.HOST, values);
    }

    /**
     * Fetch records that have <code>profile BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfProfile(String lowerInclusive, String upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.PROFILE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>profile IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchByProfile(String... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.PROFILE, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchByCreateTime(LocalDateTime... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>modified_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchRangeOfModifiedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ServiceDiscovery.SERVICE_DISCOVERY.MODIFIED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modified_time IN (values)</code>
     */
    public List<com.leryn.gateway.data.tables.pojos.ServiceDiscovery> fetchByModifiedTime(LocalDateTime... values) {
        return fetch(ServiceDiscovery.SERVICE_DISCOVERY.MODIFIED_TIME, values);
    }
}
